import React from 'react';
import $ from 'jquery';
import firebase from 'firebase';

class Registration extends React.Component {
    constructor(props){
        super(props);
        this.db = this.props.db;
        this.handleSignupClick = this.handleSignupClick.bind(this);
    }

    signup(email, password){
        const db = this.props.db;
        
        db.auth().createUserWithEmailAndPassword(email, password).then(()=>{

        }).catch((error) =>{
            console.log(error);
        });
    }

    saveUserInfo(userID, username, name, email){
        this.setState({
            userID,
            username,
            name,
            email
        });

        return this.db.database().ref(`users/${userID}`).set({
            userID,
            username,
            name,
            email
        });
    }

    handleSignupClick(db, saveUserInfo){
        let user;

        // Grab the users login info.
        const loginDetails = {
            email: $('#email').val(),
            password: $('#password').val(),
            username: $('#email').val(),
            name: $('#name').val(),
            // UserID will be generated by firebase and sent back in success. 
            userID: ''
        },
        auth = db.auth();

        auth.createUserWithEmailAndPassword(
            loginDetails.email, 
            loginDetails.password).catch((error) =>{
                new Error(`from handleSignupClick: ${error}`);
        }).then(function(){
        user = auth.currentUser;
        if (user){
            saveUserInfo(
                user.uid,
                loginDetails.username, 
                loginDetails.name,
                loginDetails.email);
            }
        });
    }

    render(){
        const handleSignupClick = this.handleSignupClick,
              db = this.db,
              saveUserInfo = this.saveUserInfo.bind(this),
              setState = this.setState;
        
        return (<div>
                <div className="intro-header intro-header-register">
                        <div className="mlb-transparent-gradient"></div>
                        <div className="site-heading">
                            <h1 className="text-shadow">Register</h1>
                            <hr className="small"/>
                            <span className="subheading">DO IT NOW!</span>
                        </div>
                </div>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div className="panel panel-sm">
                                <div className="panel-heading">
                                    <h2>Come be a part of the Magic Leap family.</h2>
                                </div>

                            <div className="panel-body">
                            <form name="signup" id="signup" onSubmit={(event)=>event.preventDefault()}>
                                <div className="row control-group">
                                    <div className="form-group col-xs-12 floating-label-form-group controls">
                                        <label>Name</label>
                                        <input type="text" className="form-control" placeholder="Name" id="name" required="" data-validation-required-message="Please enter your name." aria-invalid="false" />
                                        <p className="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div className="row control-group">
                                    <div className="form-group col-xs-12 floating-label-form-group controls">
                                        <label>Email Address</label>
                                        <input type="email" className="form-control" placeholder="Email Address" id="email" required="" data-validation-required-message="Please enter your email address." />
                                        <p className="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div className="row control-group">
                                    <div className="form-group col-xs-12 floating-label-form-group controls">
                                        <label>Password</label>
                                        <input type="password" className="form-control" placeholder="Password" id="password" required="" data-validation-required-message="Please enter your password." />
                                        <p className="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div className="row control-group">
                                    <div className="form-group col-xs-12 floating-label-form-group controls">
                                        <label>Confirm Password</label>
                                        <input type="password" className="form-control" placeholder="Password confirmation" id="password-confirm" required="" data-validation-required-message="Please enter your password." />
                                        <p className="help-block text-danger"></p>
                                    </div>
                                </div>
                                <br />
                                <div id="success"></div>
                                <div className="row">
                                    <div className="form-group col-xs-12 clearfix">
                                        <button onClick={()=>this.handleSignupClick(db, saveUserInfo)} type="submit" className="btn btn-success pull-right">Signup!</button>
                                    </div>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>)
    }
}

export default Registration;